stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - params.yaml
    params:
      - data_ingestion.test_size
      - data_ingestion.random_state
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/interim/preprocessed_train.csv
      - data/interim/preprocessed_test.csv
  
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/interim/preprocessed_train.csv
      - params.yaml
    params:
      - feature_engineering.max_features
      - feature_engineering.n_grams
    outs:
      - data/processed/train_tfidf.csv
      - models/tfidf_vectorizer.pkl